FRONTENDBOOTCAMP-13th/Final-12-WhySIBI

src/app/globals.css
src/components/_common/Header.tsx
src/components/_common/Menu_Navigation.tsx
src/components/reviews/review_info/review_info.tsx
src/components/reviews/review_list.tsx
src/data/actions/replies.ts
src/types/replies.ts

리뷰 수정은 기능 구현 목록에서 팀내 인원들과 상의 후 제거하고 삭제 기능만 구현
resolves #82

[Feature] - 리뷰 삭제 기능 추가

---

api/bruno/WhySIBI/게시물 상세 조회.bru
src/app/globals.css
src/app/products/[id]/page.tsx
src/components/Buttons/Button_basic.tsx
src/components/Buttons/Button_question.tsx
src/components/Shopping_detail/Inquiry_list.tsx
src/components/Shopping_detail/Product_inquiry.tsx
src/components/Shopping_detail/Product_review.tsx
src/components/Shopping_detail/Review_list.tsx
src/components/Shopping_detail/Shopping_form.tsx
src/types/shopping_detail.ts

- 판매자 문의의 모달창을 제작하였습니다. 서버액션은 구현예정
- 리뷰 정렬기능을 더 추가하였습니다.
resolves #26

[feature] - 판매자 문의 모달창 제작, 리뷰정렬 기능 

---

src/components/_common/Menu_Navigation.tsx
src/components/bookmark_list/bookmark_list.tsx
src/components/edit_info_form/EditInfoForm.tsx
src/components/my_page_menu_list/my_page_menu_list.tsx
src/components/order_list/order_list.tsx
src/components/reviews/review_list.tsx
src/data/actions/bookmark.ts
src/data/actions/file.ts
src/data/actions/inqury.ts
src/data/actions/order.ts
src/data/actions/post.ts
src/data/actions/products.fetch.ts
src/data/actions/products.ts
src/data/actions/replies.ts
src/data/actions/user.ts
src/data/functions/post.ts
src/hooks/useAxiosInstance.tsx
src/types/post.ts
src/zustand/menuStore.ts

- [] 커밋 메시지 컨벤션에 맞게 작성했습니다.
resolves #45

[Fix] env파일에 맞게 액션함수 수정

---

src/app/community/[boardType]/PostCard_Item.tsx
src/app/community/[boardType]/[_id]/CommentItem.tsx
src/app/community/[boardType]/[_id]/CommentNew.tsx
src/app/community/[boardType]/[_id]/PostDetail.tsx
src/app/community/[boardType]/[_id]/edit/EditForm.tsx
src/app/community/[boardType]/[_id]/page.tsx
src/app/community/[boardType]/new/RegistForm.tsx
src/components/Button_back.tsx
src/data/actions/post.ts

[deploy] - 배포 테스트

---

src/app/community/[boardType]/[_id]/page.tsx

🐛 fix: 반복된 컴포넌트 삭제

---

README.md

 [docs] readme.md 초안 작성

---

.github/workflows/push-to-another-repository.yml

[deploy] -  배포테스트

---

src/app/community/[boardType]/PostCard_Item.tsx
src/app/community/[boardType]/[_id]/CommentDeleteForm.tsx
src/app/community/[boardType]/[_id]/CommentItem.tsx
src/app/community/[boardType]/[_id]/CommentList.tsx
src/app/community/[boardType]/[_id]/CommentNew.tsx
src/app/community/[boardType]/[_id]/CommentSection.tsx
src/app/community/[boardType]/[_id]/page.tsx
src/app/community/[boardType]/new/TagProductModal.tsx
src/components/Detail_posts/Detail_similar.tsx
src/components/Main_component/main_product_slider.tsx
src/components/Write_posts/Image_uploader.tsx
src/components/_common/Header.tsx
src/components/product_search/product_search_list.tsx
src/components/product_search/product_search_title.tsx
src/data/functions/post.ts
src/zustand/productSearchStore.ts

- 비슷한 상품 찾기 기능 연결
- 검색 페이지 코드 수정 (비슷한 상품 찾기 연결)
- 로딩 ui 추가
- 에러 수정
resolves #126

[feature] - 비슷한 상품 찾기 기능 연결 및 로딩 ui 추가

---

src/app/community/[boardType]/[_id]/CommentNew.tsx

- CommentNew 빌드에러 수정
resolves #147

🐛 fix: 댓글 빌드에러 수정

---

src/app/community/[boardType]/PostCardList.tsx
src/app/community/[boardType]/[_id]/CommentItem.tsx
src/app/community/[boardType]/[_id]/CommentNew.tsx
src/app/community/[boardType]/[_id]/PostDetail.tsx
src/app/community/[boardType]/[_id]/page.tsx
src/components/Detail_posts/Detail_other.tsx
src/components/Detail_posts/Detail_similar.tsx
src/components/Detail_posts/Detail_swiper.tsx
src/components/_common/Header.tsx
src/components/_common/Menu_Navigation.tsx
src/components/_common/category.tsx
src/components/best_talk_list/best_talk_card/best_talk_card.tsx
src/components/best_talk_list/best_talk_list.tsx
src/components/login_form/login.form.tsx
src/components/talk_detail/talk_detail.tsx
src/components/talk_list/talk_list.tsx

Refectoring/146 refectoring/johyunsoo

---

src/app/(user)/my_page/layout.tsx
src/app/cart/page.tsx
src/app/community/[boardType]/page.tsx
src/app/globals.css
src/app/layout.tsx
src/app/not-found.tsx
src/app/page.tsx
src/app/products/[id]/page.tsx
src/app/service/page.tsx
src/app/shopping/best/[mainCategoryId]/page.tsx
src/app/shopping/best/page.tsx
src/app/shopping/category/[mainCategoryId]/[subCategoryId]/page.tsx
src/app/shopping/category/[mainCategoryId]/page.tsx
src/app/shopping/category/page.tsx
src/app/shopping/recommend/page.tsx
src/components/Main_component/main_bottom_slider.tsx
src/components/Main_component/main_recommend_box.tsx
src/components/_common/Footer.tsx
src/components/_common/Header.tsx
src/components/_common/Menu_Navigation.tsx
src/components/_common/category.tsx

코드를 리팩토링 했습니다
- 전체적인 레이아웃 구조 
- 전체적인 반응형 리팩토링 
resolves #144

[Refeactoring] 코드 리팩토링

---

src/app/cart/Cart_address_input.tsx
src/app/cart/Cart_all_delete_button.tsx
src/app/cart/Cart_delete_button.tsx
src/app/cart/Cart_main.tsx
src/app/cart/Cart_purchase_button.tsx
src/app/products/[id]/page.tsx
src/components/Shopping_detail/Product_cart_button.tsx
src/components/Shopping_detail/Product_purchase_button.tsx
src/components/Shopping_detail/Shopping_form.tsx
src/components/_common/Header.tsx
src/components/login_form/login.form.tsx
src/components/product_component/Like_badge.tsx
src/components/product_component/product_card.tsx
src/components/register_form/register_form.tsx
src/data/actions/bookmark.ts
src/data/actions/create_cart_action.ts

- 상품 상세 페이지 toastUI리팩토링
- 상세에서 찜하기 기능 리렌더링 안되도록 리팩터링
- 비로그인 상태 찜하기 시도시 error toastUI추가
resolves #143

[Refeactoring] - 상품상세, 장바구니 리팩토링

---

src/app/community/[boardType]/PostCardList.tsx
src/components/_common/Menu_Navigation.tsx
src/components/_common/category.tsx

🐛 fix: 빌드 에러 수정

---

src/app/community/[boardType]/PostCardList.tsx
src/components/Detail_posts/Detail_similar.tsx

[fix] - 병합 에러 수정

---

src/components/login_form/login.form.tsx

- 로그인 토스트 ui 버그수정
resolves #162

[fix] - 로그인 toastUI버그 수정

---

README.md
src/app/globals.css
src/components/Main_component/main_banner_slider.tsx
src/components/banner_card.tsx

- 메인 배너 버그 수정 및 리드미 완성
- 
resolves #161

[fix] 메인 배너 버그 수정 및 리드미 완성

---

api/dbinit/team/data.json
src/components/Main_component/main_product_slider.tsx
src/components/product_component/product_card.tsx

[Refeac] - 메인페이지 리팩토링

---

src/components/Main_component/main_product_slider.tsx
src/components/Main_component/main_recommend_box.tsx
src/components/Shopping_best/Shopping_best_section.tsx
src/components/Shopping_detail/Shopping_form.tsx
src/components/Shopping_list/Shopping_products_list.tsx
src/components/Shopping_list/Shopping_selling_slider.tsx
src/components/Shopping_recommend/recommend_box.tsx
src/components/product_search/product_random_tag.tsx
src/components/product_search/product_search_button.tsx
src/components/product_search/product_search_list.tsx

- 상품 목록, 상품 상세 할인율 0% 오류 해결
- 상품 검색 모달 반응형
resolves #190

[Refactoring] 최최종 리팩토링

---

src/app/community/[boardType]/[_id]/edit/EditForm.tsx
src/app/community/[boardType]/new/RegistForm.tsx
src/app/page.tsx
src/components/Main_component/main_category_section.tsx
src/components/Main_component/main_product_slider.tsx
src/components/Main_component/main_recommend_section.tsx
src/components/Main_component/main_showroom.tsx
src/components/Write_posts/subject_category_select.tsx
src/components/_common/Menu_Navigation.tsx

♻️ refactor: 리팩토링

---

src/app/community/[boardType]/[_id]/PostDetail.tsx
src/app/page.tsx
src/components/Detail_posts/Detail_swiper.tsx
src/components/Main_component/main_category_section.tsx
src/components/Shopping_detail/Like_button.tsx
src/components/Shopping_detail/Product_Info.tsx
src/components/Shopping_detail/Shopping_detail.tsx
src/components/Shopping_detail/Shopping_form.tsx
src/components/Shopping_list/Shopping_banner_card.tsx
src/components/_common/Header.tsx
src/components/bookmark_list/bookmark_list.tsx
src/components/my_inqury_list/my_inqury_list.tsx
src/components/reviews/review_list.tsx

♻️ refactor:  반응형 리팩토링

---

src/app/search/page.tsx
src/components/Main_component/main_recommend_box.tsx
src/components/Shopping_list/Shopping_products_list.tsx
src/components/Shopping_list/Shopping_selling_slider.tsx
src/components/product_search/product_search_button.tsx
src/zustand/menuStore.ts

- 검색창 모달 반응형 리팩토링
resolves #195

♻️ refactor: 검색창 모달 반응형 리팩토링

---

src/app/community/[boardType]/PostCard_Item.tsx
src/components/Shopping_detail/Inquiry_list.tsx
src/components/Shopping_detail/Product_inquiry.tsx
src/components/Shopping_detail/Product_review.tsx
src/components/Shopping_list/Shopping_products_list.tsx
src/components/Shopping_list/Shopping_selling_slider.tsx
src/components/Shopping_recommend/recommend_box.tsx

- 상품 찜하기 할때 스켈레톤 UI나오지 않게 수정
- 집들이 페이지 북마크 할때마다 새로고침안되게 수정
- 집들이 페이지 로그인 안했을때 북마크하면 에러toastUI 나오게 리팩토링
- 상품리뷰, 판매자문의 반응형 UI리팩토링
resolves #197

[Bug] - 집들이 페이지 북마크 리팩토링, 찜하기 스켈레톤 리팩토링, 반응형UI리팩토링

---

src/app/(user)/(account)/regiester/page.tsx
src/components/register_form/register_form.tsx

🎨 feat: 회원가입시에 회원가입 타입 변환 기능 추가

---

api/bruno/WhySIBI/로그인.bru
src/app/order/Order_info.tsx
src/app/order/Order_item.tsx
src/app/order/Order_main.tsx
src/app/order/Order_purchase_button.tsx
src/app/order/Order_receipt.tsx
src/app/order/page.tsx
src/components/Shopping_detail/Product_purchase_button.tsx
src/data/actions/create_each_purchase_action.ts
src/types/puchase.ts

[feat] - 주문서 페이지 제작
